---
###########################
###########################
## Linter GitHub Actions ##
###########################
###########################
name: Lint code samples

#
# Documentation:
# https://help.github.com/en/articles/workflow-syntax-for-github-actions
#

#############################
# Start the job on all push #
#############################
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

###############
# Set the Job #
###############
jobs:
  build:
    # Name the Job
    name: Lint code samples
    # Set the agent to run on
    runs-on: ubuntu-latest

    ##################
    # Load all steps #
    ##################
    steps:
      ##########################
      # Checkout the code base #
      ##########################
      - name: Checkout Code
        uses: actions/checkout@latest

      ################################
      # Run Linter against code base #
      ################################
      - name: Lint code samples
        uses: github/super-linter@latest
        env:
          VALIDATE_ALL_CODEBASE: true
          VALIDATE_SHELL_SHFMT: false # Ignore .sh files
          VALIDATE_BASH: false # # Ignore .sh files
          VALIDATE_BASH_EXEC: false # # Ignore .sh files
          DEFAULT_BRANCH: master
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}